### ISSUE TITLE
Persist/Export data for vendors and purpose

### ISSUE THREAD

**Issue by coolharsh55** [Perdu/vendorlistexplorer#1]
Currently (I think) the data is populated on server as a MySQL table, and is updated periodically. Exporting this data can provide useful information about practices regarding IAB and consent online. Although the data can be (theoretically) pulled from IAB APIs/servers at any time, persisting also provides a 'backup'. How to implement this?

**Comment by Perdu** [comment]
Hi! I'm not sure I understand what you want. You can make backups using mysqldump, and raw json files are not deleted by the import script

**Comment by coolharsh55** [comment]
I was referring to exporting those dumps outside mysql, so as to publish them, reuse them elsewhere with other data (non IAB), or just make them available. E.g. /data/v68.json or /data/current.json or /data_v68.zip The alternative to this is for someone to setup the server + database just to get the data out?

**Comment by Perdu** [comment]
Well you can download all vendorlists in a single line of bash:
```bash
for i in $(seq 1 68) ; do wget -O vendorlistv2_"$i".json https://vendorlist.consensu.org/v2/archives/vendor-list-v"$i".json ; done
```

**Comment by coolharsh55** [comment]
Thanks, I feel like an idiot for not realising this! Close the issue?

**Comment by Perdu** [comment]
Yes, but I feel like I should add this to the readme anyway
